[workspace]
members = ["crates/library", "crates/cli"]
resolver = "2"

# [patch.crates-io]
# kutil-cli = { path = "../rust-kutil/crates/cli" }
# kutil-std = { path = "../rust-kutil/crates/std" }
# read-url = { path = "../rust-read-url" }
