[workspace]
members = ["crates/library", "crates/macros", "crates/cli"]
resolver = "3"

[patch.crates-io]
kutil-cli = { path = "../rust-kutil/crates/cli" }
read-url = { path = "../rust-read-url/crates/library" }

[profile.release]
strip = "debuginfo"
lto = true
