[package]
edition = "2024"

name = "compris"
description = "Composite Primitive Schema (CPS) for Rust"
version = "0.0.4"
rust-version = "1.86"

license = "MIT OR Apache-2.0"
repository = "https://github.com/tliron/rust-compris"
documentation = "https://docs.rs/compris"
authors = ["Tal Liron"]

readme = "../../README.md"

categories = [
    "data-structures",
    "encoding",
    "parsing",
] # https://crates.io/category_slugs
keywords = ["cps"]

[dependencies]
anstream = "0.6.18"
base64 = "0.22.1"
borc = { optional = true, version = "0.6.0" }
compris-macros = { optional = true, version = "=0.0.2" }
duplicate = "2.0.0"
kutil-std = "=0.0.4"
kutil-cli = "=0.0.6"
num-traits = "0.2.19"
ordered-float = "5.0.0"
rmp = { optional = true, version = "0.8" }
rmp-serde = { optional = true, version = "1.3.0" }
saphyr-parser = { optional = true, version = "0.0.4" }
serde = { optional = true, version = "1.0.219" }
serde-xml-rs = { optional = true, version = "0.8.0" }
serde_yml = { optional = true, version = "0.0.12" }      # YAML (eventually replace with saphyr-serde?)
struson = { optional = true, version = "0.6.0" }
thiserror = "2.0.12"
tracing = "0.1.41"
tynm = "0.2.0"

[dev-dependencies]
# For examples/serialize.rs
serde = { version = "1.0.219", features = ["derive"] }

[features]
default = ["yaml", "json", "xml", "cbor", "messagepack"]
yaml = ["dep:saphyr-parser"]
json = ["dep:struson"]
xml = []
cbor = ["dep:borc"]
messagepack = ["dep:rmp"]

# Not default
derive = ["dep:compris-macros"]
serde = [
    "ordered-float/serde",
    "dep:rmp-serde",       # TODO: only when messagepack
    "dep:serde",
    "dep:serde-xml-rs",    # TODO: only when xml
    "dep:serde_yml",       # TODO: only when yaml
    "struson?/serde",
]

[[example]]
name = "resolve_basic"
required-features = ["derive"]

[[example]]
name = "resolve_enum"
required-features = ["derive"]

[[example]]
name = "resolve_advanced"
required-features = ["derive"]

[[example]]
name = "serialize"
required-features = ["serde"]

[[example]]
name = "deserialize"
required-features = ["serde", "serde/derive"]
# TODO: vscode rust-analyzer causes errors due to serde/derive requirement
# for now we will put it in main dependencies

# https://stackoverflow.com/a/61417700
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
