#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

# sudo dnf install python-devel

"$HERE/build-python-venv" "$@"
into_python

pip install --upgrade pip
pip install --upgrade maturin[patchelf]

if [ "$1" != -r ]; then
    # See: https://github.com/PyO3/maturin/issues/2951
    # MATURIN_ARGS='--profile=dev --strip=false'
    MATURIN_ARGS=--profile=dev
fi

function build () {
    cd "$ROOT/$1"

    # --sdist
    maturin build \
        --compatibility=pypi \
        $MATURIN_ARGS

    # .tar.gz?
    pip install --force-reinstall ../target/wheels/*.whl
}

build python
